output_folder: ./results        # Main output folder. All the outputs (log, plots, models) will be saved to this folder
sub_folders:                    # Subfolder names for model, plot, and log                  
  model : mdl
  plot  : plot
  log   : log
  
file_suffix: test               # str, all the leaf output file name will contain this suffix
maxiter: 30000                  # Total number of epochs
save_model_every: 100           # Save models and logs per [such] iterations
save_plot_every: 1000           # Save plots per [such] iterations, maxiter / save_plot_every better not exceed 500
stdout : 1                      # 0: print to screen, 1: print to log file

problem:                        # Parameters for problem
  name  : Chemistry 
  train_file_path : ./problems/chemistry_train.txt
  test_file_path : ./problems/chemistry_test.txt
  regs:                           # regularization multipliers of different losses composing objective function
    pde     : 1.0e-3
    boundary: 1.0e-3
    fitting : 1
  n_constrs: 10                    # number of constraints ---
  constraint_type : other       # pde, or fitting, or boundary, or other
  batch_size: 0.5               # str full or int batch_size #TODO
  nn_name       : FCN           # neural network name. This should be a class in nn_architecture.py
  nn_input      : 5             # x, t, u_zero
  nn_output     : 4
  nn_parameters:                # The keys can be different for different neural network
    n_hidden: 64
    n_layers: 3
  t_max: 10                      # null or int. Largest time.
  t_discretization: 100         # null or int. discretization of time
  fitting_sample_percentage : 0.6
  n_initial_conditions : 100     # int. number of initial condition generated
  n_test_initial_conditions: 1
  
optimizer:
  name : sqp                  # adam or sgd or sqp 
  lr    : 1.0e-3
  mu    : 1.0e-7
  beta2 : 0.999
  pretrain: null              # null; or dict with keys: epoch_start and file_suffix
  alpha_type: 'c_adam'         # 'ada', 'adam', 'c_ada', 'c_adam' 
  beta1 : 0.1
      
      