output_folder: ./results        # Main output folder. All the outputs (log, plots, models) will be saved to this folder
sub_folders:                    # Subfolder names for model, plot, and log                  
  model : mdl
  plot  : plot
  log   : log
  
file_suffix: test               # str, all the leaf output file name will contain this suffix
n_epoch: 30000                  # Total number of epochs
save_model_every: 100           # Save models and logs per [such] epochs
save_plot_every: 1000           # Save plots per [such] epochs, n_epoch / save_plot_every better not exceed 500
stdout : 1                      # 0: print to screen, 1: print to log file
batch_seed : 5                       # number of runs; valid only when batch_size is not 'full'

problem:                        # Parameters for problem
  name  : Spring
  regs:                           # regularization multipliers of different losses composing objective function
    pde     : 1.0e-4
    boundary: 0
    fitting : 1
  n_constrs: 3                    # number of constraints ---
  constrs_area_percent: [0.14, 0.4, 0.7]     # list of length n_constrs. the constraints applies at percentage of t_max
  constraint_type : pde       # pde, or fitting
  batch_size: 0.5            # str full or int batch_size in [1,n_train_obj_samples_per_group['pde']]
  nn_name       : FCN           # neural network name. This should be a class in nn_architecture.py
  nn_input      : 1
  nn_output     : 1
  nn_parameters:                # The keys can be different for different neural network
    n_hidden: 32
    n_layers: 3
  t_max: 1                      # null or int. Largest time.
  t_discretization: 500         # null or int. discretization of time
  dim_x: 0                      # int. dimension of domain
  x_max: null                   # null or list of largest x of number dim_x
  x_discretization: null        # null or list of discretization x of number dim_x
  n_group_pde_parameters: 1     # int. number of group of pde parameters
  n_train_obj_samples_per_group: # number of samples of different losses composing objective function
    pde     : 30
    boundary: 0
    fitting : 10
  fitting_area_percent: 0.4      # the largest percentage of range of t_max that fitting data covers, unique for spring

  
optimizer:
  name : sqp                  # adam or sgd or sqp 
  lr    : 1.0e-3
  mu    : 1.0e-7
  beta2 : 0.999
  alpha_type: 'c_adam'         # 'ada', 'adam', 'c_ada', 'c_adam' 
  beta1 : 0.9
  pretrain: null              # null; or dict with keys: epoch_start and file_suffix
      